name: ClockUtil
main: com.rayzr522.clockutil.ClockUtil
version: 1.2
description: >
             A plugin that gives you multiple utilities by right clicking with a clock
commands:
  clockutil:
    description: All the ClockUtil commands
  menu:
    description: Opens a ClockUtil menu
  itemtype:
    description: Tells you what type and data the item in your hand has